### ISSUE TITLE
TimeOutError: Did not manage to upload package.  Failing

### ISSUE THREAD

**Issue by cpauvert** [conda-forge/r-plnmodels-feedstock#1]
Issue: Azure tests fail because of lack of upload to anaconda.

<br/>
Environment : `Azure linux_64_r_base3.6` and R4 
<br/>

The error was mentioned by the bot: https://github.com/conda-forge/r-plnmodels-feedstock/commit/a08e87d8e2f94055bd085f050e033a0673a1d3d1#commitcomment-43842366

The package was correctly [installed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235295&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=758) and [loaded](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235295&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=1055) but from what I understand, the issue comes from the upload of the package to anaconda.org ([link](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235295&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=1101)). They were 9 trys, all failed and Azure quitted on error.

I will upgrade the build number (as per the README and this [issue](https://github.com/conda-forge/spdlog-feedstock/issues/28)) to try to solve

**Comment by chrisburr** [comment]
I think I've fixed this and retriggered the build in https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235552&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e

I'll check back later but feel free to ping me if you notice it has failed again.

**Comment by cpauvert** [comment]
Great thanks @chrisburr ! @dpryan79 in #4 triggered also the build and it seems to run fine (waiting for win64 as we write)

**Comment by chrisburr** [comment]
Success! https://anaconda.org/conda-forge/r-plnmodels/files

If you're generally interested, the process which was failing is described [here](https://github.com/conda-forge/cfep/blob/master/cfep-13.md). The issue was caused by me making a mistake yesterday when moving the staged-recipes feedstock creation job to Azure Pipelines. If you see more issues like this let me know.

**Comment by cpauvert** [comment]
Perfect! Thank you for the fix and the doc! I'll close the issue, but to be sure, there's nothing to be done rn (merge #4 or bump the build number)?

**Comment by chrisburr** [comment]
Nope, you shouldn't need to bumpy the build number or merge anything else until you have actual changes.

**Comment by cpauvert** [comment]
Ok thank you @chrisburr and @dpryan79
